include(CMakeForceCompiler)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_WIN32_THREADS_INIT 0)
set(CMAKE_USE_PTHREADS_INIT 1)
set(THREADS_PREFER_PTHREAD_FLAG ON)

set(CMAKE_C_COMPILER /home/boccolarg/microros_ws/firmware/zephyr-sdk/aarch64-zephyr-elf/bin/aarch64-zephyr-elf-gcc)
set(CMAKE_CXX_COMPILER /home/boccolarg/microros_ws/firmware/zephyr-sdk/aarch64-zephyr-elf/bin/aarch64-zephyr-elf-g++)

set(CMAKE_C_FLAGS_INIT "-c -I/home/boccolarg/microros_ws/firmware/zephyr_apps/microros_extensions/../../zephyrproject/zephyr/include/posix -I/home/boccolarg/microros_ws/firmware/zephyr_apps/microros_extensions/../../build/zephyr/include/generated -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/include -I/home/boccolarg/microros_ws/firmware/build/zephyr/include/generated -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/soc/arm -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/lib/libc/common/include -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/include/zephyr/posix -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/lib/posix/options/getopt/. -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/soc/arm/qemu_cortex_a53/. -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/subsys/net/l2 -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/subsys/net/lib/dns/. -I/home/boccolarg/microros_ws/firmware/build/modules/libmetal/libmetal/lib/include -I/home/boccolarg/microros_ws/firmware/zephyrproject/modules/lib/open-amp/open-amp/lib/include -DKERNEL -D__ZEPHYR__=1 -D__LINUX_ERRNO_EXTENSIONS__ -DPICOLIBC_DOUBLE_PRINTF_SCANF -DK_HEAP_MEM_POOL_SIZE=16777216 -fno-strict-aliasing -Os -imacros /home/boccolarg/microros_ws/firmware/build/zephyr/include/generated/autoconf.h -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-a53 -mabi=lp64 --sysroot=/home/boccolarg/microros_ws/firmware/zephyr-sdk/aarch64-zephyr-elf/aarch64-zephyr-elf -imacros /home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wformat -Wno-format-zero-length -Wdouble-promotion -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/home/boccolarg/microros_ws/firmware/zephyr_apps/apps/ping_pong=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/boccolarg/microros_ws/firmware/zephyrproject=WEST_TOPDIR -ffunction-sections -fdata-sections -moverride=tune=no_ldp_stp_qregs --specs=picolibc.specs -D_POSIX_THREADS -std=c99 -isystem/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/lib/libc/common/include" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_INIT "-c -I/home/boccolarg/microros_ws/firmware/zephyr_apps/microros_extensions/../../zephyrproject/zephyr/include/posix -I/home/boccolarg/microros_ws/firmware/zephyr_apps/microros_extensions/../../build/zephyr/include/generated -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/include -I/home/boccolarg/microros_ws/firmware/build/zephyr/include/generated -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/soc/arm -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/lib/libc/common/include -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/include/zephyr/posix -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/lib/posix/options/getopt/. -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/soc/arm/qemu_cortex_a53/. -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/subsys/net/l2 -I/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/subsys/net/lib/dns/. -I/home/boccolarg/microros_ws/firmware/build/modules/libmetal/libmetal/lib/include -I/home/boccolarg/microros_ws/firmware/zephyrproject/modules/lib/open-amp/open-amp/lib/include -DKERNEL -D__ZEPHYR__=1 -D__LINUX_ERRNO_EXTENSIONS__ -DPICOLIBC_DOUBLE_PRINTF_SCANF -DK_HEAP_MEM_POOL_SIZE=16777216 -fno-strict-aliasing -Os -fcheck-new -fno-exceptions -fno-rtti -imacros /home/boccolarg/microros_ws/firmware/build/zephyr/include/generated/autoconf.h -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-a53 -mabi=lp64 --sysroot=/home/boccolarg/microros_ws/firmware/zephyr-sdk/aarch64-zephyr-elf/aarch64-zephyr-elf -imacros /home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wno-unused-but-set-variable -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/home/boccolarg/microros_ws/firmware/zephyr_apps/apps/ping_pong=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/boccolarg/microros_ws/firmware/zephyrproject=WEST_TOPDIR -ffunction-sections -fdata-sections -moverride=tune=no_ldp_stp_qregs --specs=picolibc.specs -D_POSIX_THREADS -isystem/home/boccolarg/microros_ws/firmware/zephyrproject/zephyr/lib/libc/common/include" CACHE STRING "" FORCE)

# set(__BIG_ENDIAN__ 0)