#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/11.5.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'lm-sensors.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'lm-sensors.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'lm-sensors.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'lm-sensors.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper rm_conffile /etc/blacklist.d/lm-sensors 1:2.9.0-14\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/modutils/i2c 1:3.0.1-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/modprobe.d/i2c 1:3.1.0-1\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/modprobe.d/lm-sensors /etc/modprobe.d/lm-sensors.conf 1:3.1.0-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/fancontrol 1:3.1.1-5\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/11.5.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/lm-sensors" ]; then
		update-rc.d lm-sensors defaults >/dev/null || exit 1
	fi
fi
# End automatically added section
