#!/bin/sh
set -e
# Automatically added by dh_systemd_start/12.1.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12.1.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'usb-gadget-getty-ttyGS0.service' 'usb-gadget.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'usb-gadget-getty-ttyGS0.service' 'usb-gadget.service' >/dev/null || true
		deb-systemd-helper unmask 'usb-gadget-getty-ttyGS0.service' 'usb-gadget.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12.1.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'usb-gadget.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'usb-gadget.service' >/dev/null || true
		deb-systemd-helper unmask 'usb-gadget.service' >/dev/null || true
	fi
fi
# End automatically added section
