#!/bin/sh

NAME=containerd
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
DAEMON_ARGS="--config /etc/containerd/containerd_default_config.toml --log-level info" # >/var/log/containerd.log"

[ -r /etc/default/$NAME ] && . /etc/default/$NAME $1

do_start() {
        echo -n "Starting $NAME: "

    	## We do kill Dockerd, as we dont need it and it just creates confusion 
    	## with the proper configuration of containerd started. We need a clean start
    	## of containerd to use our config file  
	/etc/init.d/S60dockerd stop 
	sleep 1
	echo "Starting containerd..."
	start-stop-daemon --start --quiet --background --make-pidfile \
                --pidfile $PIDFILE --exec ${DAEMON} -- ${DAEMON_ARGS} \
                && echo "OK" || echo "FAIL"
}

do_stop() {
        echo -n "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                sleep 1
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

